# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Continous Integration with Github Actions

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    #action de login
    - name: Login to Docker Hub
      uses: docker/login-action@v2.0.0
      with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
         
    #action do java
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'adopt'
        cache: maven
        
    #action do maven
    - name: Build Application JAR
      working-directory: ./api-curso
      run: mvn clean package -DskipTests

    #action do docker compose
    - name: Docker Compose Build
      #working-directory: ./api-curso  se docker compose estiver em localizacao diferente
      run: docker compose build

    #action que da o push no Docker Hub
    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/api-curso:latest ${{ secrets.DOCKER_USERNAME }}/api-curso:${{ github.run_id }}

        docker push ${{ secrets.DOCKER_USERNAME }}/api-curso:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/api-curso:latest
